### ISSUE TITLE
بهینه‌سازی کد برای دقت بالا

### ISSUE THREAD

**Issue by mohadese-developer** [mahdi-tavakoli-anodyneGROUP/Collage-AI-2#15]
بهینه‌سازی کد با optimizer برای رسیدن به دقت بالای 80٪ از طریق تنظیم پارامترهای آموزشی.
![79٪](https://github.com/user-attachments/assets/257d8554-8049-4d15-8fd6-3a78e792e7e3)

**Comment by kamyabrafiaei** [comment]
یبار ترین کرم با مدل یولو 8 n بعد اومدم وزن هاشو تو یک پوشه ریختم و برای اموزش بار دومم از همون وزنا استفاده کردم و 85 در صد شد و بهتر شد
