### ISSUE TITLE
مشخص کردن نواحی سینوسی فک و دندان در تصاویر OPG

### ISSUE THREAD

**Issue by mohadese-developer** [mahdi-tavakoli-anodyneGROUP/Collage-AI-2#5]
پس از ثبتنام در ناحیه کاربری خود در روبوفلو, در پروژه  dental-decay وارد و سپس تعداد 200 عدد تصویر را نواحی سینوس را در فک و دندان مشخص فرمایید.
نمونه تصویر :
![5780662600869200416](https://github.com/user-attachments/assets/91df922a-7511-4a33-929c-882bf8cdbf76)

**Comment by kamyabrafiaei** [comment]
با توجه به مشخص نبودن نواحی سینوسی منتظر هستم تا اموزش داشته باشم برای این نواحی بعد لیبل زدن را شروع کنم.

**Comment by kamyabrafiaei** [comment]
انجام شد شب در تاریخ 9 oct ساعت 21:50 alpha1
